# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-05 19:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hostels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hostel_name', models.CharField(max_length=200)),
                ('Area', models.CharField(max_length=50)),
                ('Category', models.CharField(max_length=200)),
                ('Price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contacts', models.IntegerField()),
                ('Email', models.EmailField(max_length=200)),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostels.Hostels')),
            ],
        ),
    ]
