# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-06 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='Owner_name',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
