# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-06 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0002_owner_owner_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='Available',
            field=models.BooleanField(default=False),
        ),
    ]
