# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-06 13:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0003_owner_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='Available',
            new_name='is_available',
        ),
    ]
